# Use official Bun image
FROM oven/bun:1.1-alpine

# Set working directory
WORKDIR /app
ENV NODE_ENV=development
# Install dependencies first for caching
COPY package.json bun.lockb* ./
RUN if [ -f bun.lockb ]; then bun install --frozen-lockfile ; else bun install; fi
COPY package.json ./
RUN bun install

# Copy application files
COPY . .

# Expose port
EXPOSE 3000

# Start development server with hot reloading
CMD ["bun", "run", "dev"]
