services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3078:3000"
    volumes:
      - .:/app
      # Exclude node_modules and build artifacts
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    

  # # Security scanning services
  # trivy:
  #   image: aquasec/trivy:latest
  #   volumes:
  #     - ./security-reports/trivy:/reports
  #   command: >
  #     sh -c "trivy filesystem --security-checks vuln,config,secret /
  #     -f json -o /reports/report-$(date +%Y%m%d).json || true"
      
  # sonarqube:
  #   image: sonarqube:community
  #   ports:
  #     - "9090:9000"
  #   environment:
  #     - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #   volumes:
  #     - ./sonarqube/data:/opt/sonarqube/data
  #     - ./sonarqube/extensions:/opt/sonarqube/extensions
  #     - ./sonarqube/logs:/opt/sonarqube/logs

  # snyk:
  #   image: snyk/snyk:node
  #   volumes:
  #     - .:/app
  #     - ./security-reports/snyk:/reports
  #   command: >
  #     sh -c "snyk test --json > /reports/report-$(date +%Y%m%d).json || true"
  #   environment:
  #     - SNYK_TOKEN=${SNYK_TOKEN}


